[tool.poetry]
name = "ct-drl-ma"
version = "0.1.0"
description = "Masters thesis on RMGC controlled by Reinforcement Learning"
authors = ["Franko Jolic"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
torch = "^2.10.0"
torchvision = "^0.25.0"
matplotlib = "^3.10.8"
tqdm = "^4.67.2"
pandas = "^3.0.0"
scipy = "^1.17.0"
scikit-learn = "^1.8.0"
numba = "^0.63.1"
jupyter = "^1.1.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
