# simulation/core/vehicles/terminal_truck.py
from datetime import datetime, timedelta
from typing import Optional
from simulation.core.containers.container import Container
from simulation.core.vehicles.truck import Truck
from simulation.core.constants import (
    STANDARD_VEHICLE_LENGTH_M,
    TERMINAL_TRUCK_TASK_DURATION_S
)
from simulation.core.enums import TerminalTruckStatus
from simulation.utils.id_generator import IDGenerator


class TerminalTruck(Truck):
    """
    Represents a terminal-owned truck for moving containers within the terminal.
    
    These trucks are specialized for moving swap bodies and trailers between
    storage positions, freeing up valuable specialized storage areas.
    
    Inherits from Truck but adds terminal-specific functionality and constraints.
    """
    
    def __init__(
        self,
        truck_id: Optional[str] = None,
        max_length: float = STANDARD_VEHICLE_LENGTH_M,
        arrival_time: Optional[datetime] = None
    ):
        """
        Initialize a new terminal truck.
        
        Args:
            truck_id: Unique identifier (auto-generated if None)
            max_length: Maximum container length capacity in meters
            arrival_time: When the truck enters service
        """
        # Initialize parent class with custom prefix
        super().__init__(
            truck_id=truck_id,
            max_length=max_length,
            arrival_time=arrival_time,
            parking_spot=None,  # Terminal trucks don't use regular parking
            prefix=None  # Will be generated by IDGenerator
        )
        
        # Override truck_id if needed for terminal truck format
        if truck_id is None:
            self.truck_id = IDGenerator.generate_terminal_truck_id()
        
        # Override status to use terminal truck statuses
        self.status = TerminalTruckStatus.IDLE
        
        # Terminal truck specific attributes
        self.current_source: Optional[str] = None
        self.current_destination: Optional[str] = None
        self.task_start_time: Optional[datetime] = None
        self.task_completion_time: Optional[datetime] = None
        
        # Terminal trucks are always for internal moves
        self.is_pickup_truck = False
        self.is_delivery_truck = False
        self.is_terminal_truck = True
    
    def add_container(self, container: Container) -> bool:
        """
        Add container (only swap bodies or trailers allowed).
        
        Args:
            container: Container to add
            
        Returns:
            True if added successfully, False otherwise
        """
        if not container:
            return False
        
        # Only swap bodies or trailers
        if not (getattr(container, "is_swap_body", False) or 
                getattr(container, "is_trailer", False)):
            return False
        
        # Terminal trucks carry one at a time
        if self.containers:
            return False
        
        return super().add_container(container)
    
    def assign_task(
        self,
        source: str,
        destination: str,
        task_time: float = None,
        current_time: datetime = None
    ) -> None:
        """
        Assign a transport task to the terminal truck.
        
        Args:
            source: Source position identifier
            destination: Destination position identifier
            task_time: Time in seconds the task will take (default: 5 minutes)
            current_time: Current simulation time
            
        Raises:
            ValueError: If parameters are invalid
        """
        if not source:
            raise ValueError("Source position must be provided")
        if not destination:
            raise ValueError("Destination position must be provided")
        if not current_time:
            raise ValueError("Current time must be provided")
        
        # Use default task time if not provided
        if task_time is None:
            task_time = TERMINAL_TRUCK_TASK_DURATION_S
        
        if task_time < 0:
            raise ValueError(f"Task time must be non-negative, got {task_time}")
        
        self.status = TerminalTruckStatus.BUSY
        self.current_source = source
        self.current_destination = destination
        self.task_start_time = current_time
        self.task_completion_time = current_time + timedelta(seconds=task_time)
    
    def complete_task(self, current_time: datetime) -> None:
        """
        Mark the current task as completed.
        
        Args:
            current_time: Current simulation time
            
        Raises:
            ValueError: If current_time is not provided
        """
        if not current_time:
            raise ValueError("Current time must be provided")
        
        # Store completion time for stats
        if not self.loading_complete_time:
            self.loading_complete_time = current_time
        
        # Reset task-specific attributes
        self.status = TerminalTruckStatus.IDLE
        self.current_source = None
        self.current_destination = None
        self.task_start_time = None
        self.task_completion_time = None
        self.containers = []  # Empty the truck
    
    def is_available(self) -> bool:
        """Check if the terminal truck is available for a new task."""
        return (
            self.status == TerminalTruckStatus.IDLE and
            len(self.containers) == 0
        )
    
    def is_busy(self) -> bool:
        """Check if the terminal truck is currently busy."""
        return self.status == TerminalTruckStatus.BUSY
    
    def __str__(self) -> str:
        """String representation of the terminal truck."""
        if not self.containers:
            container_str = "Empty"
        else:
            container_ids = ", ".join(c.container_id for c in self.containers)
            container_str = f"Carrying: {container_ids}"
        
        status_str = f"status: {self.status.value}"
        
        if self.status == TerminalTruckStatus.BUSY and self.current_source:
            status_str += f" ({self.current_source} -> {self.current_destination})"
        
        return f"Terminal Truck {self.truck_id}: {container_str}, {status_str}"
    
    def __repr__(self) -> str:
        """Developer-friendly representation."""
        return (
            f"TerminalTruck(id={self.truck_id}, "
            f"containers={len(self.containers)}, "
            f"status={self.status.value})"
        )